#! /usr/bin/env python3

import sys

alpha = "a b c d e f g h i j k l m n o p q r s t u v w x y z".split(" ")

# lazy lazy lazy

if len(sys.argv) != 2:
    print("SINGLE LETTER")
    sys.exit()
elif len(sys.argv[1]) != 1:
    print("SINGLE CHAR")
    sys.exit()

char_ = sys.argv[1].lower()
for i in range(26):
    if alpha[i] == char_:
        print("value: ", i+1)
        sys.exit()


 
print("ENTER A VALID LETTER YOU FUCKING NONCE")
