#! /usr/bin/env python3

import subprocess



# TODO this is the command to get the name of the wifi
# /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I | awk -F: '/ SSID/{print $2}'

if __name__ == '__main__':
    output = subprocess.check_output(["airport", "-I", "|", "awk", "\'/ SSID/{$2}\'"])

    print("")
    print("=== [CHECKING WIFI] ===")
    print("...")
    #index_of_SSID = output.find("SSID: ")
    #print(index_of_SSID)
    
    final = output.decode("utf-8")

    index_of_SSID = final.find(" SSID: ")
    final = final[index_of_SSID+6:]
    str_list = final.split ()
    wifi = str_list[0]
    print("=== [CURRENT WIFI IS: " + wifi + " ] ===")
    print("...")

    if wifi == "csu-eid" or wifi == "State" or wifi == "Eat":
        print("=== [LOGGING ON!] ===")
        print("...")
        subprocess.call(["ssh", "-X", "cademccu@montpelier.cs.colostate.edu"])
        # montpelier, riyadh, kabul, kinshasa, dhaka
    else:
        print("Need to change wifi")


