#! /usr/bin/env python3

import subprocess
import sys
''' 
This script just runs the ssh command for csu
computer science building logins.
'''

# https://www.cs.colostate.edu/~info/machines
logins = ["montpelier", "riyadh", "kabul", "kinshasa", "dhaka", "bismarck"]

def getList():
    """
    Gets the list of computers to specify at login
    """
    print("------------------------------")
    for i in range(len(logins)):
        print(str(i) + " - " + logins[i])
    print("------------------------------")

if __name__ == '__main__':
    
    num = 0
    if len(sys.argv) > 1:
        if sys.argv[1] == "-l":
            getList()
            sys.exit(0)
        num = int(sys.argv[1])

    subprocess.call(["ssh", "-X", "cademccu@" + logins[num] + ".cs.colostate.edu"])

    # todo modify for big data options
    # random selction??
    # specify option?
