#! /usr/bin/env python3
#


import sys

if len(sys.argv) != 2:
    print("[USAGE]  wordcount <text_document>\n")
    sys.exit(0)

count = 0

with open(sys.argv[1], "r") as f:
    line = f.readline()
    while line:
        count += len(line.split(" "))
        line = f.readline()

print("--------------------------------------------------------------------------")
print("WORD COUNT:  " + str(count))
print("--------------------------------------------------------------------------")

        
